Use MSVC compiler flags only with MSVC
pywinrt/python-winsdk pull request #31
Opened 2023-04-06 18:55 UTC by mimi89999

2023-04-07 00:21 UTC, dlech requested changes

2023-04-07 00:21 UTC, dlech commented on CMakeLists.txt
> +if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
I think we can simplify this to the following:

```suggestion
if (MSVC)
```

2023-04-07 00:21 UTC, dlech commented on CMakeLists.txt
> +endif()
It wouldn't hurt to add an `else()` with `add_compile_options(-Werror)` for clang/gcc compile options.

2023-04-07 00:21 UTC, dlech commented on CMakeLists.txt
> +if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
While we are touching this, let's move this into the same if statement above.

2023-04-07 13:46 UTC, dlech commented on CMakeLists.txt
> +if ("MSVC")
If it is in quotes, doesn't that make it a string (which is always false)? Shouldn't it be unquoted to use the variable name instead?

```suggestion
if (MSVC)
```

2023-04-08 16:43 UTC, merged

2023-04-08 16:43 UTC, dlech commented
Nice, thanks.

2023-04-08 17:15 UTC, mimi89999 commented
@dlech Thanks for merging this. Could you please update the `pywinrt` bindings in this repo?